// AUTO-GENERATED by _gen-data.js — 从 posts/article-*.html 提取，请勿手改。
// 重新生成: node _gen-data.js
const BLOG_ARTICLES = [
  {
    "id": 67,
    "title": "面向嵌入式平台的 CLAHE 预处理加速可行性分析",
    "year": "2026",
    "category": "技术性文档",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-67.html",
    "reading": "1470 字 · 约 6 分钟"
  },
  {
    "id": 66,
    "title": "读《我们仨》",
    "year": "2026",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-66.html",
    "reading": "1885 字 · 约 7 分钟"
  },
  {
    "id": 65,
    "title": "大一总结",
    "year": "2026",
    "category": "年度总结",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-65.html",
    "reading": "1834 字 · 约 7 分钟"
  },
  {
    "id": 64,
    "title": "中考 + 高一总结",
    "year": "2023",
    "category": "年度总结",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-64.html",
    "reading": "1284 字 · 约 5 分钟"
  },
  {
    "id": 63,
    "title": "谁守望谁？——《麦田里的守望者》中\"守望者\"意象的重释",
    "year": "2026",
    "category": "学术性论文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-63.html",
    "reading": "1377 字 · 约 9 分钟"
  },
  {
    "id": 62,
    "title": "两种\"伟大\"的歧途：《了不起的盖茨比》与《远大前程》中\"Great\"寓意的再审视",
    "year": "2026",
    "category": "学术性论文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-62.html",
    "reading": "3033 字 · 约 22 分钟"
  },
  {
    "id": 61,
    "title": "作文《这样的人，让我（敬佩）》",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-61.html",
    "reading": "759 字 · 约 3 分钟"
  },
  {
    "id": 60,
    "title": "原来如此",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-60.html",
    "reading": "814 字 · 约 3 分钟"
  },
  {
    "id": 59,
    "title": "鸢尾花开的夏天",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-59.html",
    "reading": "2543 字 · 约 9 分钟"
  },
  {
    "id": 57,
    "title": "夜",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-57.html",
    "reading": "415 字 · 约 2 分钟"
  },
  {
    "id": 56,
    "title": "小城日落",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-56.html",
    "reading": "1120 字 · 约 4 分钟"
  },
  {
    "id": 55,
    "title": "细微之处见真情（原版）",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-55.html",
    "reading": "767 字 · 约 3 分钟"
  },
  {
    "id": 54,
    "title": "细微之处见真情",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-54.html",
    "reading": "1089 字 · 约 4 分钟"
  },
  {
    "id": 53,
    "title": "武汉，我们想你",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-53.html",
    "reading": "1205 字 · 约 5 分钟"
  },
  {
    "id": 52,
    "title": "《时光事》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-52.html",
    "reading": "1473 字 · 约 6 分钟"
  },
  {
    "id": 51,
    "title": "《雨》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-51.html",
    "reading": "6150 字 · 约 21 分钟"
  },
  {
    "id": 50,
    "title": "《缘》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-50.html",
    "reading": "18098 字 · 约 61 分钟"
  },
  {
    "id": 49,
    "title": "温情让美好长久",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-49.html",
    "reading": "939 字 · 约 4 分钟"
  },
  {
    "id": 48,
    "title": "死侍",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-48.html",
    "reading": "1969 字 · 约 7 分钟"
  },
  {
    "id": 46,
    "title": "书斋铭",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-46.html",
    "reading": "112 字 · 约 1 分钟"
  },
  {
    "id": 45,
    "title": "社团之争",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-45.html",
    "reading": "5160 字 · 约 18 分钟"
  },
  {
    "id": 44,
    "title": "三格情书-我喜欢你，因为你的样子",
    "year": "2021",
    "category": "现代诗",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-44.html",
    "reading": "206 字 · 约 1 分钟"
  },
  {
    "id": 43,
    "title": "如梦令·寻就",
    "year": "2021",
    "category": "古诗词",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-43.html",
    "reading": "44 字 · 约 1 分钟"
  },
  {
    "id": 42,
    "title": "沁园春",
    "year": "2021",
    "category": "古诗词",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-42.html",
    "reading": "112 字 · 约 1 分钟"
  },
  {
    "id": 41,
    "title": "浅谈自己的责任",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-41.html",
    "reading": "327 字 · 约 2 分钟"
  },
  {
    "id": 40,
    "title": "逆行路上，你我相伴",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-40.html",
    "reading": "657 字 · 约 3 分钟"
  },
  {
    "id": 39,
    "title": "闹剧（其二）",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-39.html",
    "reading": "1819 字 · 约 7 分钟"
  },
  {
    "id": 38,
    "title": "闹剧",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-38.html",
    "reading": "1677 字 · 约 6 分钟"
  },
  {
    "id": 37,
    "title": "那双美丽的眼睛",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-37.html",
    "reading": "838 字 · 约 3 分钟"
  },
  {
    "id": 36,
    "title": "老胡传",
    "year": "2021",
    "category": "纪念",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-36.html",
    "reading": "200 字 · 约 1 分钟"
  },
  {
    "id": 35,
    "title": "九上期中作文 成功的经历，也很重要",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-35.html",
    "reading": "743 字 · 约 3 分钟"
  },
  {
    "id": 34,
    "title": "唤我阿离",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-34.html",
    "reading": "832 字 · 约 3 分钟"
  },
  {
    "id": 33,
    "title": "故去的老院",
    "year": "2021",
    "category": "散文",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-33.html",
    "reading": "3097 字 · 约 11 分钟"
  },
  {
    "id": 32,
    "title": "给自己的最好礼物",
    "year": "2021",
    "category": "散文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-32.html",
    "reading": "916 字 · 约 4 分钟"
  },
  {
    "id": 31,
    "title": "个人篇",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-31.html",
    "reading": "5189 字 · 约 18 分钟"
  },
  {
    "id": 30,
    "title": "芙蕖",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-30.html",
    "reading": "551 字 · 约 2 分钟"
  },
  {
    "id": 29,
    "title": "封宅记",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-29.html",
    "reading": "822 字 · 约 3 分钟"
  },
  {
    "id": 28,
    "title": "读北岛《过节》",
    "year": "2021",
    "category": "学术性论文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-28.html",
    "reading": "1259 字 · 约 5 分钟"
  },
  {
    "id": 27,
    "title": "作文-钢铁是怎样炼成的",
    "year": "2021",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-27.html",
    "reading": "783 字 · 约 3 分钟"
  },
  {
    "id": 26,
    "title": "爱夜说 2020年4月16日语文作业",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-26.html",
    "reading": "183 字 · 约 1 分钟"
  },
  {
    "id": 25,
    "title": "2020年6月21日",
    "year": "2021",
    "category": "随笔",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-25.html",
    "reading": "437 字 · 约 2 分钟"
  },
  {
    "id": 24,
    "title": "《一棵通往天堂的樟树》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-24.html",
    "reading": "2351 字 · 约 8 分钟"
  },
  {
    "id": 22,
    "title": "《行走》",
    "year": "2021",
    "category": "散文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-22.html",
    "reading": "977 字 · 约 4 分钟"
  },
  {
    "id": 21,
    "title": "《三色堇》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-21.html",
    "reading": "1853 字 · 约 7 分钟"
  },
  {
    "id": 20,
    "title": "《三角梅》",
    "year": "2021",
    "category": "散文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-20.html",
    "reading": "935 字 · 约 4 分钟"
  },
  {
    "id": 19,
    "title": "《礼物》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-19.html",
    "reading": "1601 字 · 约 6 分钟"
  },
  {
    "id": 18,
    "title": "《仇》",
    "year": "2021",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-18.html",
    "reading": "3884 字 · 约 13 分钟"
  },
  {
    "id": 16,
    "title": "作文4-走自食其力路    谱自强不息歌",
    "year": "2022",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-16.html",
    "reading": "805 字 · 约 3 分钟"
  },
  {
    "id": 15,
    "title": "读书笔记2 长安十二时辰",
    "year": "2022",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-15.html",
    "reading": "1428 字 · 约 5 分钟"
  },
  {
    "id": 14,
    "title": "读书笔记1 局外人",
    "year": "2022",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-14.html",
    "reading": "1928 字 · 约 7 分钟"
  },
  {
    "id": 13,
    "title": "必修上册-古诗单元-生命之歌",
    "year": "2022",
    "category": "作文",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-13.html",
    "reading": "641 字 · 约 3 分钟"
  },
  {
    "id": 12,
    "title": "2060——一个会呼吸的年代",
    "year": "2022",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-12.html",
    "reading": "1652 字 · 约 6 分钟"
  },
  {
    "id": 11,
    "title": "《中秋词》",
    "year": "2022",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-11.html",
    "reading": "511 字 · 约 2 分钟"
  },
  {
    "id": 10,
    "title": "《长夜行》",
    "year": "2022",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-10.html",
    "reading": "1320 字 · 约 5 分钟"
  },
  {
    "id": 9,
    "title": "《无题》",
    "year": "2022",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-9.html",
    "reading": "122 字 · 约 1 分钟"
  },
  {
    "id": 7,
    "title": "M星上的最后一夜",
    "year": "2023",
    "category": "小说",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-7.html",
    "reading": "1662 字 · 约 6 分钟"
  },
  {
    "id": 6,
    "title": "《花间辞》",
    "year": "2023",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-6.html",
    "reading": "513 字 · 约 2 分钟"
  },
  {
    "id": 5,
    "title": "《风桥夜题》",
    "year": "2023",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-5.html",
    "reading": "128 字 · 约 1 分钟"
  },
  {
    "id": 4,
    "title": "《钗头凤·懒卷帘》",
    "year": "2023",
    "category": "古诗词",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-4.html",
    "reading": "256 字 · 约 1 分钟"
  },
  {
    "id": 3,
    "title": "语文学业考忽觉毕业将至有感而乱作",
    "year": "2024",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-3.html",
    "reading": "221 字 · 约 1 分钟"
  },
  {
    "id": 2,
    "title": "青玉案·春雷乍动小池寒",
    "year": "2024",
    "category": "古诗词",
    "lang": "zh",
    "classical": true,
    "url": "posts/article-2.html",
    "reading": "274 字 · 约 1 分钟"
  },
  {
    "id": 1,
    "title": "故然慢",
    "year": "2024",
    "category": "古诗词",
    "lang": "zh",
    "classical": false,
    "url": "posts/article-1.html",
    "reading": "1781 字 · 约 6 分钟"
  },
  {
    "id": 0,
    "title": "When...",
    "year": "2025",
    "category": "现代诗",
    "lang": "en",
    "classical": false,
    "url": "posts/article-0.html",
    "reading": "682 字 · 约 5 分钟"
  }
];
