// AUTO-GENERATED by _gen-wiki.js — 从 wiki/**/*.md 提取，请勿手改。
// 重新生成: node _gen-wiki.js
const BLOG_WIKI = [
  {
    "id": 1,
    "title": "Introduction to Blue_Wiki",
    "cat": "basics",
    "catLabel": "基础入门帖",
    "group": "开篇",
    "slug": "intro",
    "src": "wiki/basics/intro.md",
    "date": "2026-09-22",
    "tags": [
      "Wiki",
      "开源"
    ],
    "order": 0,
    "reading": "820 字 · 约 4 分钟"
  },
  {
    "id": 2,
    "title": "Wiki 写作指南",
    "cat": "basics",
    "catLabel": "基础入门帖",
    "group": "入门",
    "slug": "wiki-writing-guide",
    "src": "wiki/basics/wiki-writing-guide.md",
    "date": "2026-09-22",
    "tags": [
      "博客",
      "Markdown"
    ],
    "order": 1,
    "reading": "397 字 · 约 2 分钟"
  }
];
