// _gen-wiki.js — 扫描 wiki/<分类>/**/*.md，生成 js/wiki-data.js（Wiki 目录唯一数据源）。
// 用法: node _gen-wiki.js   （新增/修改 .md 后重跑即可同步首页 Wiki 栏）
// 约定：wiki/circuits=电子电路, wiki/it=信息技术, wiki/basics=基础入门帖；
//       分类下的一级子目录名即侧栏分组（也可用 frontmatter group: 覆盖）；
//       文件名/目录名建议用 ASCII，非 ASCII 时侧栏深链退化为 <cat>-N。
const fs = require("fs");
const path = require("path");

const ROOT = "wiki";
const CATEGORIES = [
  { cat: "circuits", label: "电子电路" },
  { cat: "it", label: "信息技术" },
  { cat: "basics", label: "基础入门帖" },
];

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fp = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(fp));
    else if (entry.name.endsWith(".md") && !entry.name.startsWith("_")) out.push(fp);
  }
  return out;
}

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!m) return { meta: {}, body: raw };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
  }
  return { meta, body: raw.slice(m[0].length) };
}

// 计字口径与 _reading.js 一致：中文 300 字/分钟、英文 200 词/分钟。
// 代码块不计入——技术类 wiki 代码密度高，算进去会让阅读时间虚高。
function countReading(body) {
  const prose = body
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/![[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/^[#>*\-|\s].*$/gm, (l) => l.replace(/[#>*|-\s]/g, " "));
  const cjk = (prose.match(/[一-鿿]/g) || []).length;
  const words = (prose.replace(/[一-鿿]/g, " ").match(/[A-Za-z0-9]+/g) || []).length;
  const zh = cjk >= words;
  const minutes = Math.max(1, Math.ceil(cjk / 300 + words / 200));
  return zh ? `${cjk} 字 · 约 ${minutes} 分钟` : `${words} words · ${minutes} min`;
}

const out = [];
let id = 0;
for (const { cat, label } of CATEGORIES) {
  const files = walk(path.join(ROOT, cat)).sort();
  const docs = files.map((fp, i) => {
    const raw = fs.readFileSync(fp, "utf8").replace(/^\uFEFF/, "");
    const { meta, body } = parseFrontmatter(raw);
    const rel = path.relative(path.join(ROOT, cat), fp).split(path.sep);
    const base = rel[rel.length - 1].replace(/\.md$/, "");
    const h1 = body.match(/^#\s+(.+)$/m);
    const src = path.posix.join(ROOT, cat, ...rel);
    return {
      id: ++id,
      title: meta.title || (h1 && h1[1].trim()) || base,
      cat,
      catLabel: meta.category || label,
      group: meta.group || (rel.length > 1 ? rel[rel.length - 2] : ""),
      slug: /^[\x20-\x7E]+$/.test(base) ? base : `${cat}-${i + 1}`,
      src,
      date: meta.date || "",
      tags: meta.tags ? meta.tags.split(/[,，]\s*/).filter(Boolean) : [],
      order: Number.isFinite(Number(meta.order)) ? Number(meta.order) : 100,
      reading: countReading(body),
    };
  });
  docs.sort((a, b) => a.order - b.order || a.group.localeCompare(b.group) || a.title.localeCompare(b.title, "zh"));
  out.push(...docs);
}

const js =
  "// AUTO-GENERATED by _gen-wiki.js — 从 wiki/**/*.md 提取，请勿手改。\n" +
  "// 重新生成: node _gen-wiki.js\n" +
  "const BLOG_WIKI = " + JSON.stringify(out, null, 2) + ";\n";
fs.mkdirSync("js", { recursive: true });
fs.writeFileSync("js/wiki-data.js", js, "utf8");

const byCat = CATEGORIES.map(({ cat, label }) => {
  const n = out.filter((d) => d.cat === cat).length;
  return `${label} ${n}`;
});
console.log(`写入 ${out.length} 条 Wiki → js/wiki-data.js  (${byCat.join(" / ")})`);
