// _gen-data.js — 从 posts/article-*.html 提取元数据，生成 js/articles-data.js（唯一数据源）。
// 用法: node _gen-data.js   （增改文章后重跑即可同步）
const fs = require("fs");
const path = require("path");
const dir = "posts";

function decode(s) {
  return s.replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ").trim();
}

// 按 id 降序：新文章（id 越大越新）排在前 → 时间视图里每一年都是「最新在上」，
// 且 renderLatestPosts() 取 slice(0,4) 时拿到的就是真正的最新 4 篇。
const files = fs.readdirSync(dir)
  .filter(f => /^article-\d+\.html$/.test(f))
  .sort((a, b) => parseInt(b.match(/\d+/)[0], 10) - parseInt(a.match(/\d+/)[0], 10));

const out = [];
for (const f of files) {
  const html = fs.readFileSync(path.join(dir, f), "utf8");
  const id = parseInt(f.match(/\d+/)[0], 10);
  const titleM = html.match(/<h1 class="article-title">([\s\S]*?)<\/h1>/);
  const title = titleM ? decode(titleM[1]) : "";
  const metaM = html.match(/<div class="article-meta">([\s\S]*?)<\/div>/);
  const spans = metaM
    ? (metaM[1].match(/<span[^>]*>[\s\S]*?<\/span>/g) || [])
        .map(s => decode(s.replace(/<[^>]+>/g, "")))
        .filter(t => t !== "·")
    : [];
  const [year, category, form, langLabel, countLabel, timeLabel] = spans;
  const reading = countLabel && timeLabel ? `${countLabel} · ${timeLabel}` : "";
  out.push({
    id,
    title,
    year: year || "",
    category: category || "",
    lang: /^English/.test(langLabel || "") ? "en" : "zh",
    classical: form === "文言文",
    url: `posts/${f}`,
    reading,
  });
}

const js =
  "// AUTO-GENERATED by _gen-data.js — 从 posts/article-*.html 提取，请勿手改。\n" +
  "// 重新生成: node _gen-data.js\n" +
  "const BLOG_ARTICLES = " + JSON.stringify(out, null, 2) + ";\n";
fs.writeFileSync("js/articles-data.js", js, "utf8");
console.log(`写入 ${out.length} 篇 → js/articles-data.js`);
console.log("样例:", JSON.stringify(out[0]), "|", JSON.stringify(out[out.length - 1]));
